---
- name: Install a package
  hosts: all

  tasks:

  - name: Install snapd # Task-1
    yum: # Module name
      name: snapd # Name of the package to be installed
      state: present # Run the playbook until the package is in present state
  
  - name: Start snapd service # Task-2
    service: # Module name
      name: snapd # Name of the service to be started
      state: started # Run the playbook until the service is in started state
      enabled: true # Set this to true to enable the service   
