---
- name: Set pasword
  hosts: all

  tasks:

  - name: Set password for a user # Task-1
    user: # Module name
      name: Sam # Name of the user
      update_password: always # Update the password if it differs
      password: "{{'pass123' | password_hash('sha512')}}" # This syntax is used to hash the password 'pass123' using 'sha512' hashing algorithm
